// Generated by CoffeeScript 1.6.3
var fs;

fs = require('fs');

module.exports = {
  read_file_sync: function(filename) {
    var error, variable;
    variable = {};
    try {
      variable.status = true;
      variable.data = fs.readFileSync(filename);
    } catch (_error) {
      error = _error;
      variable.status = false;
      variable.error = 'Error reading file #{filename} : #{error}';
    }
    return variable;
  }
};
