// Generated by CoffeeScript 1.6.3
var crypto, fs, x, xslt;

x = require('libxmljs');

xslt = require('node_xslt');

crypto = require('crypto');

fs = require('./read_file');

module.exports = {
  validate_schema: function(filename) {
    var err, error, is_valid, xml, xml_string, xsd, xsd_string;
    xsd = fs.read_file_sync('schemas/cfdv32.xsd');
    if (!xsd.status) {
      return xsd;
    }
    xml = fs.read_file_sync(filename);
    if (!xml.status) {
      return xml;
    }
    try {
      xsd_string = x.parseXmlString(xsd.data);
    } catch (_error) {
      err = _error;
      return {
        status: false,
        error: err
      };
    }
    try {
      xml_string = x.parseXmlString(xml.data);
    } catch (_error) {
      error = _error;
      return {
        status: false,
        error: error
      };
    }
    is_valid = xml_string.validate(xsd_string);
    return {
      status: is_valid,
      error: [],
      xml: xml_string
    };
  },
  get_cadena_original: function(xml) {
    var cadena_original, err, factura, params, transformedString;
    factura = xslt.readXmlString(xml);
    try {
      cadena_original = xslt.readXsltFile('schemas/cadenaoriginal_3_2.xslt');
    } catch (_error) {
      err = _error;
      return {
        status: false,
        error: err
      };
    }
    params = [];
    transformedString = xslt.transform(cadena_original, factura, params);
    return {
      status: true,
      cadena_original: transformedString,
      error: []
    };
  },
  get_digest: function(cadena_original) {
    var digest, shasum;
    shasum = crypto.createHash('sha1');
    shasum.update(cadena_original, 'utf8');
    digest = shasum.digest('hex');
    return {
      status: true,
      digest: digest
    };
  },
  sign_digest: function(certificado, digest) {
    var key, pem, sign, signature;
    pem = fs.read_file_sync(certificado);
    if (!pem.status) {
      return pem;
    }
    pem = pem.data;
    key = pem.toString('ascii');
    sign = crypto.createSign('RSA-SHA256');
    sign.update(digest);
    signature = sign.sign(key, 'base64');
    return {
      status: true,
      signature: signature
    };
  },
  sign_cfdi: function(xml, certificado) {
    var cfdi, digest, result, signature;
    cfdi = this.validate_schema(xml);
    if (!cfdi.status) {
      return {
        status: false,
        errors: ['Invalid xml, not schema structure']
      };
    }
    result = this.get_cadena_original(cfdi.xml);
    if (!result.status) {
      return {
        status: false
      };
    }
    digest = this.get_digest(result.cadena_original);
    signature = this.sign_digest(certificado, digest.digest);
    return {
      status: true,
      signature: signature
    };
  }
};
